#!/bin/bash
# bptool v2.0 - an interactive tool to modify android build.prop files
# Copyright (C) 2014  Chuck Davis <oldsoldier@gmal.com>

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301,USA.

#declare array for build.prop.settings
declare -a prop_settings

#Populate array
prop_settings[0]=`grep -i "ro.build.display.id" build.prop | head -n 1 | cut -d'=' -f2`
prop_settings[1]=`grep -i "ro.product.model" build.prop | head -n 1 | cut -d'=' -f2`		
prop_settings[2]=`grep -i "ro.build.date" build.prop | head -n 1 | cut -d'=' -f2`
prop_settings[3]=`grep -i "ro.build.date.utc" build.prop | head -n 1 | cut -d'=' -f2`
prop_settings[4]=`grep -i "ro.build.version.incremental" build.prop | head -n 1 | cut -d'=' -f2`

#displays current prop settings
function display_prop_settings(){
					echo ""
					echo "Current build.prop entries"
					echo "--------------------------"
					echo "ROM name (ro.build.display.id): "${prop_settings[0]}
					echo "Product model/device Name (ro.product.model): "${prop_settings[1]}
					echo "Build date (ro.build.date): "${prop_settings[2]}
					echo "UTC build date (ro.build.date.utc): "${prop_settings[3]}
					echo "Incremental version(ro.build.version.incremental): "${prop_settings[4]}
					echo "--------------------------"
					echo ""
				}

#exits and displays xda thread
function quit_bptool(){
			echo ""			
			echo "Thanks for using bptool"
			echo "XDA thread- http://forum.xda-developers.com/showthread.php?t=2682238"
			echo ""
			exit 0
			}

#start bptool
clear
echo "Welcome to BPTOOL, a quick build.prop updater for ROM Modders"

#check for build.prop

if [ ! -f build.prop ];then
	echo ""
	echo "build.prop not found."
	echo "Please execute this script from your working_directory/system dir."
	quit_bptool
fi

display_prop_settings

echo "Make a selection"
while :; do
echo "1 - Change ROM name/version"
echo "2 - Change product model / device name"
echo "3 - Update build dates"
echo "v - View current settings"
echo "x - exit"

echo -n "Selection: "
read SELECTION
	case "$SELECTION" in
		"1")
			echo "Enter new ROM name"
			read NAME
			sed -i "/ro.build.display.id/ c\ro.build.display.id=${NAME}" build.prop
			echo ro.build.display.id changed to $NAME
			#update array
			prop_settings[0]=$NAME
			;;
		"2")
			echo "Enter new product model /device name"
			read PRODUCTMODEL
			sed -i "/ro.product.model/ c\ro.product.model=${PRODUCTMODEL}" build.prop
			echo ro.build.display.id changed to $PRODUCTMODEL
			#update array
			prop_settings[1]=$PRODUCTMODEL
			;;
		"3")
			#get dates
			UTCDATE=`date +%s`
			BUILDDATE=`date --date="@${UTCDATE}"`
			INCREMENTAL=${prop_settings[0]}-`date +%Y%m%d.%H%M%S`

			#update build date	
			sed -i "/ro.build.date=/ c\ro.build.date=${BUILDDATE}" build.prop
			echo "ro.build.date changed to $BUILDDATE"
			#update array
			prop_settings[2]=$BUILDDATE
			
			# update UTC DATE			
			sed -i "/ro.build.date.utc/ c\ro.build.date.utc=${UTCDATE}" build.prop
			echo "ro.build.date.utc changed to $UTCDATE"
			# update array
			prop_settings[3]=$UTCDATE			

			#update incremental build
			sed -i "/ro.build.version.incremental/ c\ro.build.version.incremental=${INCREMENTAL}" build.prop
			echo "ro.build.version.incremental changed to $INCREMENTAL"
			# update array
			prop_settings[4]=$INCREMENTAL
			;;
		"v")
			display_prop_settings
			;;
		
		"x")
			quit_bptool
			;;
		*)
			echo "Invalid selection. Please select from the following options:"
			echo ""
			;;
	esac
done